#!/bin/bash
# task 1: readelf -SW testing

for file in ELF_examples/*; do
    echo "-->ELF: $file"
    readelf -SW $file | cat -e
    echo "-->$?"
    ./1-hreadelf $file | cat -e
    echo "-->$?"
    diff <(readelf -SW $file | cat -e) <(./1-hreadelf $file | cat -e)

    echo "-->return or ctrl+d to continue"
    read
done;
